package com.gapperdan.hellospock.sample;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'da55296' at '3/25/16 2:22 PM' with Gradle 2.0
 *
 * @author da55296, @date 3/25/16 2:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
