package com.gapperdan.hellospock.sample;
import org.junit.Test;

import com.gapperdan.hellospock.sample.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'da55296' at '3/25/16 2:22 PM' with Gradle 2.0
 *
 * @author da55296, @date 3/25/16 2:22 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
